### ISSUE TITLE
A bunch of bugs (Omega2+)

### ISSUE THREAD

**Issue by WereCatf** [OnionIoT/Onion-Console#19]
1. changing password doesn't work
2. the "Enable Wi-Fi" checkbox for WiFi is always unchecked, doesn't actually reflect the configuration
3. reboot doesn't work (just logs you out of Console)
4. shutdown doesn't work (just logs you out of Console)
5. on the left-hand menu-bar the button above the settings-one doesn't work, and neither do the two below it (onion-console-terminal, onion-console-editor and onion-console-webcam are not installed by the initial setup. Why have the icons in the bar for them, if they aren't installed?)
6. after the initial setup is done and if there is no firmware-upgrade to install, the setup-thingamabob just hangs there with the message "You have successfully set up your Omega! Please wait while the console is installed." -- the text never changes to reflect that the console has already finished installing, just tells  you to wait forever.

**Comment by nickfode** [comment]
To Number 1:
It seems like changing pw isn't working because chpasswd is missing
`change-password -user root -password test -verify test`
prompts
`line 86: chpasswd: not found`

**Comment by WereCatf** [comment]
I finally got around to taking a closer look and it seems none of onion-console-terminal, onion-console-editor or onion-console-webcam are installed and that's why the icons on the left-hand side bar aren't working.

**Comment by dClauzel** [comment]
Password can be change without problem via terminal, using `passwd`.

**Comment by WereCatf** [comment]
@dClauzel And? This is about the web-UI, not the terminal.

**Comment by dafoink** [comment]
I would say that the console needs alot of work.  I would try to install the console and it spins forever.  I also get problems where it has all the apps stating that they need to be installed.  you click on install, it spins and says that is it installed and to refresh.  you do that and try to go into the app and it then says to install (tried this with the console, editor, etc)

I then restored and started over and now I get broken image links.  Just seems that it is early for this and it isnt quite finished.

**Comment by WereCatf** [comment]
@dafoink I would say the whole point behind making bug-reports and giving feedback is to help them improve it. Just twiddling with one's thumbs, sitting idle and hoping they'll notice bugs or shortcomings themselves doesn't really help anyone.

**Comment by dafoink** [comment]
@WereCatf not my intention to twiddle thumbs (not sure if you were trying to chastise me for my post or not).  I was trying to find out a way to post a picture to this so that they can see what I am seeing.  Right now, the console isn't usable.  so, I am trying to submit issues as I see them.  and in the meantime work around them (or try to fix myself).  but one of the selling points of the onion is the console so that non-coders can manage the device.

**Comment by WereCatf** [comment]
No, I wasn't trying to chastise or insult anyone, including you. I was just 
saying it's a good thing people complain and voice their opinion on things 
they feel are lacking.

**Comment by dafoink** [comment]
sounds good.  sorry, I wasn't sure :)

the console really needs some work.  I was hoping to start using the onion2 for a project that I am currently using ESP8266 for since I have the need for a wifi hotspot as well as posting data to an MQTT server.  but, I don't see onion2 as being ready for that yet.

**Comment by greenbreakfast** [comment]
can you please separate these into their own issues? makes it much easier to track on our end
